networks:
  shared_network:
    driver: bridge

services:
  expo-frontend:
    container_name: friday-expo-frontend
    build:
      context: ./frontend/mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/mobile:/app
    networks:
      - shared_network
    depends_on:
      - updater

  updater:
    container_name: friday-updater
    build:
      context: ./updater
      dockerfile: Dockerfile
    volumes:
      - ./updater:/app
    networks:
      - shared_network
    restart: always