networks:
  shared_network:
    driver: bridge

services:
  expo-frontend:
    container_name: friday-expo-frontend
    build:
      context: ./frontend/mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/mobile:/app
      - /app/node_modules
    networks:
      - shared_network