networks:
  shared_network:
    driver: bridge

services:
  friday-frontend:
    container_name: friday-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    networks:
      - shared_network
    depends_on:
      - friday-updater

  friday-updater:
    container_name: friday-updater
    build:
      context: ./updater
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - shared_network
    restart: always